server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8083"
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/student/**
        - id: dep-service
          uri: lb://dep-service
          predicates:
            - Path=/department/**
